---
title: "SPatial Age Structued Model"
author: "Dan Ovando"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Background

# Examples

## Simple MPA Example

```{r}
library(tidyverse)
library(FishLife)
library(spasm)
library(ggridges)
library(gganimate)


fish <-
  create_fish(
    scientific_name = "Atractoscion nobilis",
    query_fishlife = T,
    mat_mode = "length",
    time_step = 1,
    sigma_r = 0,
    steepness = 0.9,
    r0 = 4290000,
    rec_ac = 0,
    adult_movement = 0,
    larval_movement = 0,
    density_dependence_form = 1
  )


fleet <- create_fleet(
  fish = fish,
  cost_cv =  0,
  cost_ac = 0,
  cost_slope = 0,
  q_cv = 0,
  q_ac = .7,
  q_slope = 0,
  fleet_model = "constant-effort",
  sigma_effort = 0,
  length_50_sel = 0.1 * fish$linf,
  initial_effort = 2000,
  profit_lags =  5,
  beta = 2,
  max_cr_ratio = 0.9,
  max_perc_change_f = 0.5,
  effort_allocation = 'simple',
  mpa_reaction = "leave"
)


simple <- spasm::sim_fishery(
  fish = fish,
  fleet = fleet,
  manager = create_manager(mpa_size = 0.2, year_mpa = 25,
                           mpa_locations = 23),
  num_patches = 100,
  sim_years = 50,
  burn_years = 1,
  time_step = fish$time_step,
  est_msy = FALSE,
  random_mpas = FALSE,
  min_size = 0.05,
  mpa_habfactor = 1,
  sprinkler = FALSE,
  keep_burn = FALSE
)

simple %>% 
  filter(year == max(year),
         mpa == TRUE) %>% 
  group_by(patch) 

plot_spasm(simple, type = "totals", font_size = 12)

```



## Complext MPA Example

```{r}
library(tidyverse)
library(FishLife)
library(spasm)
library(ggridges)
library(gganimate)


fish <-
  create_fish(
    scientific_name = "Atractoscion nobilis",
    query_fishlife = T,
    mat_mode = "length",
    time_step = 1,
    sigma_r = 0,
    steepness = 0.9,
    r0 = 4290000,
    rec_ac = 0,
    density_movement_modifier = 0,
    adult_movement = 4,
    larval_movement = 30,
    density_dependence_form = 3
  )


fleet <- create_fleet(
  fish = fish,
  cost_cv =  0,
  cost_ac = 0,
  cost_slope = 0,
  q_cv = 0,
  q_ac = .7,
  q_slope = 0,
  fleet_model = "constant-effort",
  sigma_effort = 0,
  length_50_sel = 0.1 * fish$linf,
  initial_effort = 20000,
  profit_lags =  5,
  beta = 2,
  max_cr_ratio = 0.9,
  max_perc_change_f = 0.5,
  effort_allocation = 'gravity'
)


set.seed(42)
complex <- spasm::sim_fishery(
  fish = fish,
  fleet = fleet,
  manager = create_manager(mpa_size = 0.2, year_mpa = 25),
  num_patches = 100,
  sim_years = 50,
  burn_years = 25,
  time_step = fish$time_step,
  est_msy = F,
  random_mpas = TRUE,
  min_size = 0.05,
  mpa_habfactor = 4,
  sprinkler = TRUE,
  keep_burn = FALSE
)

plot_spasm(complex, type = "patch")

complex %>% 
  filter(year == max(year)) %>% 
  group_by(patch) %>% 
  summarise(biomass = sum(biomass),
            mpa = unique(mpa)) %>% 
  ggplot(aes(patch, biomass, fill = mpa)) + 
  geom_col()


```


## MPAs + Fleet Dynamics


```{r}

library(tidyverse)
library(FishLife)
library(spasm)
library(ggridges)
library(gganimate)
fish <-
  create_fish(
    scientific_name = "Atractoscion nobilis",
    query_fishlife = T,
    mat_mode = "length",
    time_step = 1,
    sigma_r = 0,
    price = 10,
    price_cv = 0,
    price_ac = 0,
    price_slope = 0,
    steepness = 0.9,
    r0 = 1000,
    rec_ac = 0,
    density_movement_modifier = 0.25,
    adult_movement = 3,
    larval_movement = 3,
    density_dependence_form = 3
  )


fleet <- create_fleet(
  fish = fish,
  cost_cv =  0,
  cost_ac = 0,
  cost_slope = 0,
  q_cv = 0,
  q_ac = .7,
  q_slope = 0,
  fleet_model = "open-access",
  sigma_effort = 0,
  length_50_sel = .2 * fish$length_50_mature,
  initial_effort = 1,
  profit_lags =  1,
  beta = 1,
  max_cr_ratio = 0.2,
  b_ref_oa = 0.9,
  max_perc_change_f = 2,
  effort_allocation = 'profit-gravity'
)


complex_fleet <- spasm::sim_fishery(
  fish = fish,
  fleet = fleet,
  manager = create_manager(mpa_size = .2, year_mpa = 30),
  num_patches = 50,
  sim_years = 50,
  burn_years = 50,
  time_step = fish$time_step,
  est_msy = FALSE,
  random_mpas = TRUE,
  min_size = 0.05,
  mpa_habfactor = 4,
  sprinkler = TRUE,
  keep_burn = FALSE,
  tune_costs = TRUE
)

plot_spasm(complex_fleet, type = "patch")
```


